name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: hello1
      id: hello1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: hello1
        setup-command: mvn test "-Dtest=TestHello"
        command: gradle test
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLO1_RESULTS: "${{steps.hello1.outputs.result}}"
      with:
        runners: hello1
